name: Build

on:
  push:
    branches: [master]

  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
      - name: Setup the code
        uses: borales/actions-yarn@v4
        with:
          cmd: install
      - name: Test the code
        uses: borales/actions-yarn@v4
        with:
          cmd: build
